import "./globals.css";
import type { Metadata } from "next";
import { Provider } from "@/providers";
import { Navbar } from "@/components/navbar";
import { Geist, Geist_Mono, Gugi } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const gugi = Gugi({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-gugi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${gugi.variable} min-h-screen flex flex-col`}
      >
        <Provider>
          <Navbar className="fixed top-0 left-0 right-0 h-20 z-50" />
          <main className="mt-20 flex-1 w-full min-h-[calc(100dvh-5rem)] flex justify-center items-center">
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
